import { MobileBudgetConfig, MobileTransaction } from '../types';
import { getBudgetWeekLabel } from './budgetWeeksService';

const currentWeek = getBudgetWeekLabel();

export const INITIAL_MOBILE_CONFIG: MobileBudgetConfig = {
  startingBalance: 15000.00,
  availableBalance: 12480.00,
  currencySymbol: '₱',
  activeWeek: currentWeek,
  autoSync: true,
};

export const INITIAL_MOBILE_TRANSACTIONS: MobileTransaction[] = [
  {
    id: 'tx_seed_1',
    date: '2026-09-08',
    time: '09:30',
    weekLabel: currentWeek,
    type: 'income',
    category: 'Salary',
    categoryIcon: '💼',
    amount: 15000.00,
    note: 'Kinsenas Sweldo',
    balanceAfter: 15000.00,
    syncStatus: 'synced',
    sheetRowIndex: 2,
  },
  {
    id: 'tx_seed_2',
    date: '2026-09-09',
    time: '12:15',
    weekLabel: currentWeek,
    type: 'expense',
    category: 'Food',
    categoryIcon: '🍚',
    amount: 245.00,
    note: 'Jollibee Chickenjoy',
    balanceAfter: 14755.00,
    syncStatus: 'synced',
    sheetRowIndex: 3,
  },
  {
    id: 'tx_seed_3',
    date: '2026-09-10',
    time: '08:45',
    weekLabel: currentWeek,
    type: 'expense',
    category: 'Transpo',
    categoryIcon: '🚗',
    amount: 80.00,
    note: 'Pamasahe Jeep at Bus',
    balanceAfter: 14675.00,
    syncStatus: 'synced',
    sheetRowIndex: 4,
  },
  {
    id: 'tx_seed_4',
    date: '2026-09-11',
    time: '14:20',
    weekLabel: currentWeek,
    type: 'expense',
    category: 'Bills',
    categoryIcon: '💡',
    amount: 1850.00,
    note: 'Meralco Kuryente',
    balanceAfter: 12825.00,
    syncStatus: 'synced',
    sheetRowIndex: 5,
  },
  {
    id: 'tx_seed_5',
    date: '2026-09-12',
    time: '11:00',
    weekLabel: currentWeek,
    type: 'expense',
    category: 'Food',
    categoryIcon: '🍚',
    amount: 345.00,
    note: 'Palengke & Gulay',
    balanceAfter: 12480.00,
    syncStatus: 'synced',
    sheetRowIndex: 6,
  },
];
